### ISSUE TITLE
Map icons are not always displayed correctly

### ISSUE THREAD

**Issue by Kjir** [ZetaTwo/aoe2replaypacker#12]
For some drafts, the map icons are not displayed correctly. Probably the aoe2cm.net prefix is always added, but sometimes the map icons are a full URL. Here an example draft: https://aoe2cm.net/draft/sdhVO

**Comment by ZetaTwo** [comment]
Good catch. At this point we should probably flesh out a "Draft" class which is created from the API response where we do a little more parsing. This would for example also be a good opportunity to add info about which map belongs to whom.
