### ISSUE TITLE
Missing icons for Hindustanis and Incas

### ISSUE THREAD

**Issue by Kjir** [ZetaTwo/aoe2replaypacker#9]
Incas and Hindustanis are missing icons in the preview of the civ draft

![image](https://github.com/ZetaTwo/aoe2replaypacker/assets/64094/56ec45cb-97b7-46fc-a9e4-ca296af1828b)

**Comment by 7AXEL** [comment]
Check out this project: https://github.com/7AXEL/Web2APK

**Comment by ZetaTwo** [comment]
Incas seems to be a naming discrepancy (incas vs inca): https://github.com/ZetaTwo/aoe2replaypacker/blob/main/src/assets/civs/menu_techtree_inca.png

Hindustanis seems to be that the icon is still named after the original use for the "indians" civ, pre split: https://github.com/ZetaTwo/aoe2replaypacker/blob/main/src/assets/civs/menu_techtree_indians.png

I'll need to update he mapping here: https://github.com/ZetaTwo/aoe2replaypacker/blob/main/src/components/CivIcon.vue
